"""Add gearbox model

Revision ID: 5955c0e71504
Revises: 688018ecdcf7
Create Date: 2026-03-14 06:46:21.728996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5955c0e71504'
down_revision: Union[str, None] = '688018ecdcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gearboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gearbox_number', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('gearbox_type', sa.Enum('WORM', 'HELICAL', 'HELICAL_BEVEL', 'PARALLEL_SHAFT', 'VARIATOR', 'INDUSTRIAL', name='gearboxtype'), nullable=False),
    sa.Column('series', sa.String(length=50), nullable=True),
    sa.Column('stages', sa.Integer(), nullable=True),
    sa.Column('input_power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('output_torque_nm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('input_speed_rpm', sa.Integer(), nullable=True),
    sa.Column('output_speed_rpm', sa.Integer(), nullable=True),
    sa.Column('service_factor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('efficiency', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('mounting_position', sa.Enum('M1', 'M2', 'M3', 'M4', 'M5', 'M6', name='mountingposition'), nullable=True),
    sa.Column('output_shaft_diameter_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('output_shaft_length_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('output_flange_type', sa.String(length=20), nullable=True),
    sa.Column('hollow_shaft', sa.Boolean(), nullable=True),
    sa.Column('oil_volume_l', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('radial_load_n', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gearboxes_gearbox_number'), 'gearboxes', ['gearbox_number'], unique=True)
    op.create_index(op.f('ix_gearboxes_id'), 'gearboxes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gearboxes_id'), table_name='gearboxes')
    op.drop_index(op.f('ix_gearboxes_gearbox_number'), table_name='gearboxes')
    op.drop_table('gearboxes')
    # ### end Alembic commands ###
