"""Add bearing_unit model

Revision ID: 688018ecdcf7
Revises: 
Create Date: 2026-03-07 08:29:15.832274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688018ecdcf7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bearing_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('shaft_diameter_mm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('housing_type', sa.Enum('PILLOW_BLOCK', 'SQUARE_FLANGE', 'TWO_BOLT_FLANGE', 'FLANGE_CARTRIDGE', 'TAKE_UP', name='housingtype'), nullable=False),
    sa.Column('housing_material', sa.Enum('CAST_IRON', 'STAINLESS_STEEL', 'PRESSED_STEEL', 'THERMOPLASTIC', name='housingmaterial'), nullable=False),
    sa.Column('a_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('e_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('i_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('g_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('l_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('s_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('b_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('dynamic_load_kn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('static_load_kn', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bearing_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bearing_id'], ['bearings.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['bearing_manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bearing_units_id'), 'bearing_units', ['id'], unique=False)
    op.create_index(op.f('ix_bearing_units_unit_number'), 'bearing_units', ['unit_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bearing_units_unit_number'), table_name='bearing_units')
    op.drop_index(op.f('ix_bearing_units_id'), table_name='bearing_units')
    op.drop_table('bearing_units')
    # ### end Alembic commands ###
